### ISSUE TITLE
Error running app.js

### ISSUE THREAD

**Issue by Whytehorse** [shaunuk/picar#4]
When I run node app.js I get the following error:
/home/pi/picar/node_modules/socket.io/lib/index.js:177
  const keysIterator = this.parentNsps.keys();
  ^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/picar/app.js:3:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
If I comment out the use strict command in index.js I get the following error:
/home/pi/picar/node_modules/socket.io/lib/index.js:179
  const run = () => {
               ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/picar/app.js:3:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by Whytehorse** [comment]
Edit: This was fixed by installing latest node. The one in the instructions is too old.

**Comment by SilverBiscuit** [comment]
Have you make it work? @Whytehorse

**Comment by Whytehorse** [comment]
yes it works
